# Generated by Django 4.1.1 on 2022-10-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Roll', models.IntegerField()),
                ('Section', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
